POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFubnVra2EiLCJpZCI6IjYzNzRhMjhmMTJkODYxZGI4Mjg4NDEzZSIsImlhdCI6MTY2ODc1Nzg1OH0.GX_F1yXnEwFqjf1QJ9h-FlxMKsNw5tYDUQSbLdVjf7o

{
  "title": "Marshmallows by Fire",
  "author": "Justus Mammonen",
  "url": "http://marshmallows-by-fire.fi",
  "likes": 2
}